In [7]:
from utilities.data_loader import load_data

train_prices, train_dates, test_prices, test_dates = load_data("./data/BTC-Daily.csv")

In [22]:
from utilities.filters import lma_filter, ema_filter, wma, sma_filter

print(sma_filter(3))
print(sum(sma_filter(3)))

print(lma_filter(3))
print(sum(lma_filter(3)))

print(ema_filter(3, 0.5))
print(sum(ema_filter(3, 0.5)))

[0.33333333 0.33333333 0.33333333]
1.0
[0.5        0.33333333 0.16666667]
1.0
[0.57142857 0.28571429 0.14285714]
1.0


In [ ]:
P = [10, 12, 11, 13, 12]
N = 3
print(wma(P, N, sma_filter(N)))
print(wma(P, N, lma_filter(N)))
print(wma(P, N, ema_filter(N, 0.5)))


[-4.33333333  3.33333333 11.         12.         12.        ]
[-0.83333333  7.33333333 11.16666667 12.16666667 12.16666667]
[ 0.71428571  8.         11.14285714 12.28571429 12.14285714]


In [18]:
import numpy as np
print(lma_filter(3))
print(np.convolve([0, 0, 1], lma_filter(3), 'valid'))
print(np.convolve([0, 1, 0], lma_filter(3), 'valid'))
print(np.convolve([1, 0, 0], lma_filter(3), 'valid'))

[0.5        0.33333333 0.16666667]
[0.5]
[0.33333333]
[0.16666667]
